### ISSUE TITLE
Feat: Our Team Page

### ISSUE THREAD

**Issue by kom-senapati** [dakshsinghrathore/Brighter-Beginnings#14]
### Describe the feature

Currently, the link doesn't take to anywhere. A page could be made where contributors of this project can be listed (manually or using a script).

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/92045934/4dad11e4-7e43-4335-992a-b7f14097e731)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [ ] I want to work on this issue

**Comment by PRITISH212121** [comment]
heyy @kom-senapati  I would like to work on this issue

**Comment by kom-senapati** [comment]
> heyy @kom-senapati I would like to work on this issue

tag daksh not me

**Comment by GauriGA** [comment]
@dakshsinghrathore Can you assign me this issue?

**Comment by gayathrik23** [comment]
@dakshsinghrathore can you assign me this issue??

**Comment by Shreyas-SAS** [comment]
well just a suggestion if I may. rather than creating a full page and displaying the default no avatar images on website and manually changing it each time, why not just use the default and premade GitHub featured page from [here](https://github.com/dakshsinghrathore/Brighter-Beginnings/graphs/contributors) instead. If you wish, I can anchor the website in a min and push the PR. a benefit with this is that it will be auto-updated each time and we get to see when and how much everyone has contributed to the project.

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/96542494/3ab07ea3-1224-4d03-b308-6e89f5cb52c7)

**Comment by Shreyas-SAS** [comment]
else I can propose some designs and maybe try to create a github actions backend for dynamic fetching of contributors stats

**Comment by dakshsinghrathore** [comment]
@Shreyas-SAS go ahead !

**Comment by Shreyas-SAS** [comment]
@dakshsinghrathore  I had researched it a bit and found out that there was no specific way to create a github action to integrate the page as different elements as cards or other. so can I go ahead with just using this page as anchored link?

**Comment by kom-senapati** [comment]
I can create the page like the following :

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/92045934/245c0af7-48eb-4b69-b57e-26c2284d1dc5)


@dakshsinghrathore I would like to work on this issue.

**Comment by Shreyas-SAS** [comment]
> I can create the page like the following :
> 
> ![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/92045934/245c0af7-48eb-4b69-b57e-26c2284d1dc5)
> 
> 
> @dakshsinghrathore I would like to work on this issue.

This actually looks great. @dakshsinghrathore please check it out.

**Comment by dakshsinghrathore** [comment]
@kom-senapati yep, looks great but do consider making it responsive.
